.TH UPDATE_SQLGREY_CONFIG "1" "Feb 2010" "Antonin Kral" "sqlgrey"
.SH "NAME"
update_sqlgrey_config \- the simple white\-list updater
.SH "SYNOPSIS"
\fBupdate_sqlgrey_config
.SH "DESCRIPTION"
.PP
\fBupdate_sqlgrey_config\fR
is a simple bash script, which downloads white\-list file from defined web server (sqlgrey.bouton.name is used by default). Host could be changed in sqlgrey.conf.
.PP
Beware of the fact that script will overwrite any local changes.
.SH "COPYRIGHT"
.PP
Copyright 2010 Antonin Kral
.SH "AUTHOR"
Antonin Kral
